version: '3.3'
services:
  gdrive:
    image: 213ogd/gdrive
    build:
      context: gdrive
      # dockerfile: ./gdrive/Dockerfile
    volumes:
      - ./gdrive/src:/app/src
    ports: 
      - "4000:4000"
    container_name: 213ogd-gdrive
    # environment:
    #   - PORT=${PORT}
    #   - MONGO_URI=${MONGO_URI}
    networks: 
      - microservices

  auth:
    image: 213ogd/login
    build:
      context: login
      # dockerfile: ./login/Dockerfile
    ports: 
      - "5000:4000"
    # environment:
    #   - PORT=${PORT}
    networks: 
      - microservices
    depends_on: 
      - authmongo

  authmongo:
    image: mongo
    volumes:
      - loginmongo:/data/db:rw
    networks: 
      - microservices

volumes: 
  loginmongo:
networks:
  microservices:
