version: '3.3'
services:
  gdrive-service:
    build:
      context: gdrive
      dockerfile: Dockerfile

  auth-service:
    build:
      context: auth
      dockerfile: Dockerfile

  gateway:  
    build:
      context: gateway
      dockerfile: Dockerfile

  authmongo:
    container_name: authmongo
    image: mongo
    restart: always
    volumes:
      - authmongo:/data/db:rw

