version: '3.3'
services:
  server:
    image: 213ogd/server
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports: 
      - "4000:4000"
    container_name: 213ogd-server
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}