version: '3.3'
services:
  gdrive:
    image: 213ogd/gdrive
    build:
      context: gdrive
      dockerfile: Dockerfile
    volumes:
      - ./gdrive/src:/app/src
    ports: 
      - "4000:4000"
    container_name: 213ogd-gdrive
    env_file:
      ./gdrive/.env
    networks: 
      - microservices

  auth:
    image: 213ogd/auth
    build:
      context: auth
      dockerfile: Dockerfile
    ports: 
      - "5000:4000"
    env_file:
        ./auth/.env
    volumes: 
      - ./auth/src:/app/src
    networks: 
      - microservices
    depends_on: 
      - authmongo

  authmongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - authmongo:/data/db:rw
    networks: 
      - microservices

volumes: 
  authmongo:
networks:
  microservices:
