version: '3.3'
services:
  gdrive-service:
    image: 213ogd/gdrive
    build:
      context: gdrive
      dockerfile: Dockerfile
    volumes:
      - ./gdrive/src:/app/src
    ports: 
      - "4001:4000"
    env_file:
      ./gdrive/.env
    networks: 
      - microservices

  auth-service:
    image: 213ogd/auth
    build:
      context: auth
      dockerfile: Dockerfile
    ports: 
      - "4002:4000"
    volumes: 
      - ./auth/src:/app/src
    networks: 
      - microservices
    depends_on: 
      - authmongo

  gateway:
    image: 213ogd/gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    volumes: 
      - ./gateway/src:/app/src
    networks: 
      - microservices
    depends_on: 
      - gdrive-service
      - auth-service

  authmongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - authmongo:/data/db:rw
    networks: 
      - microservices

volumes: 
  authmongo:
networks:
  microservices:
