name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          touch .env
          echo "PORT=5000" >> .env
          echo "MONGO_URI=mongodb+srv://213OGD:fK0uRT1SJ5bk@cluster213.l0oyn.mongodb.net/files?retryWrites=true&w=majority" >> .env
          cat .env
          ls
          docker build -t 213ogd/server .
          docker push 213ogd/server
