name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Environment
        run: |
          touch .env
          echo "PORT=5000" >> .env
          echo "MONGO_URI=mongodb+srv://213OGD:fK0uRT1SJ5bk@cluster213.l0oyn.mongodb.net/files?retryWrites=true&w=majority" >> .env
          cat .env
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 213ogd/server:latest
          
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
